service: desafio-api-pokedex

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 3
  # iam:
  #   role:
  #     statements:
  #     - Effect: Allow
  #       Action:
  #         - dynamodb:Query
  #         - dynamodb:Scan
  #         - dynamodb:GetItem
  #         - dynamodb:PutItem
  #         - dynamodb:UpdateItem
  #         - dynamodb:DeleteItem
  #       Resource: 
  #         - !GetAtt treinadoresTable.Arn
  #         - !GetAtt PokemonsTable.Arn
  # environment:
  #   TREINADORES_TABLE: !Ref treinadoresTable
  #   POKEMONS_TABLE: !Ref PokemonsTable

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
  pythonRequirements:
    dockerizePip: false

functions:
  - ${file(./src/controllers/functions.yml)}

# Aqui é onde as tabelas são criadas automaticamente
# resources:
#   Resources:
#     TreinadoresTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:service}-treinadores-${self:provider.stage}
#         BillingMode: PAY_PER_REQUEST    # Paga só pelo uso, sem provisionar
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S            # S = String
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH               # Partition Key
#     PokemonsTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${self:service}-pokemons-${self:provider.stage}
#         BillingMode: PAY_PER_REQUEST
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH